#
# Module manifest for module 'Pipelines'
#
# Generated by: jeffrey@patton-tech.com
#
# Generated on: 12/29/2023
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule         = 'Pipelines.dll'

    # Version number of this module.
    ModuleVersion      = '2.0.0.0'

    # Supported PSEditions
    # CompatiblePSEditions = @()

    # ID used to uniquely identify this module
    GUID               = 'cff00216-d0d0-4565-af27-31d9c0400884'

    # Author of this module
    Author             = 'jeffrey@patton-tech.com'

    # Company or vendor of this module
    CompanyName        = 'Patton-Tech.com'

    # Copyright statement for this module
    Copyright          = '12/29/2023 1:34:06 AM'

    # Description of the functionality provided by this module
    Description        = 'A PowerShell module for working with ADO/Github pipelines'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion = '7.0'

    # Name of the PowerShell host required by this module
    PowerShellHostName = 'ConsoleHost'

    # Minimum version of the PowerShell host required by this module
    PowerShellHostVersion = '7.0'

    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    DotNetFrameworkVersion = '7.0'

    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    ClrVersion = '7.0'

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules = @()

    # Assemblies that must be loaded prior to importing this module
    RequiredAssemblies = @('.\Pipelines.dll')

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules = @()

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    # FunctionsToExport = @()

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport    = @('New-AdoPipeline','New-AdoStage','New-AdoJob','New-AdoTemplate','New-AdoPool',
                           'New-GhaWorkflow','New-GhaJob','New-GhaStep')

    # Variables to export from this module
    VariablesToExport  = '*'

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    # AliasesToExport = @()

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData        = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            # Tags = @()

            # A URL to the license for this module.
            LicenseUri = 'https://github.com/mod-posh/Pipelines/blob/main/LICENSE'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/mod-posh/Pipelines'

            # A URL to an icon representing this module.
            IconUri = 'https://avatars.githubusercontent.com/u/71194126?s=400&u=a35e523b8c927a8583a21177771a0cda9b3eabc0&v=4'

            # ReleaseNotes of this module
            ReleaseNotes = @('Add Github Action support','','-BUG','','- Rename test files for ado cmdlets #53','- Cmdlets were not testing null properly #52','- Missed NewStage rename #51','- Fix pester tests #50','- Make sure help version get''s incremented  #49','- Resolve name clash, betwen classes and cmdlets #48','','-DOCUMENTATION','','- Add Step Cmdlet Help #43','- Add Job Cmdlet Help #42','- Add Workflow Cmdlet Help #41','','-ENHANCEMENT','','- Add support for Github Actions #','- Add Step PesterTest #46','- Add Job PesterTest #45','- Add Workflow PesterTest #44','- Add Step Cmdlet Help #43','- Add Job Cmdlet Help #42','- Add Workflow Cmdlet Help #41','- Add Step Cmdlet #40','- Add Job Cmdlet #39','- Add Workflow Cmdlet #38','- Add Steps to YamlSerializer #37','- Add Job to YamlSerializer #36','- Add Workflow to YamlSerializer #35','- Add Steps class #34','- Add Job class #33','- Add Workflow class #32','')

            # Prerelease string of this module
            # Prerelease = ''

            # Flag to indicate whether the module requires explicit user acceptance for install/update/save
            RequireLicenseAcceptance = $false

            # External dependent modules of this module
            # ExternalModuleDependencies = @()

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    HelpInfoURI        = 'https://raw.githubusercontent.com/mod-posh/Pipelines/v2.0.0.0/cabs/'

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.

}